### ISSUE TITLE
Risk Analysis: RCM-SW-11

### ISSUE THREAD

**Issue by Mefl** [makers-for-life/makair#63] opened 2020-03-29 15:35 UTC
The device shall monitor the battery voltage and trig a medium priority alarm X when autonomy remaining is at 40% (at least 30 min)

**Comment by cmdm** [comment] 2020-03-31 19:58
Update after meeting 30 march:
The device shall monitor the battery voltage and trig a medium priority alarm 21 when voltage is at 12.3V

**Comment by dsferruzza** [comment] 2020-04-06 12:46
@cmdm This looks like a duplicate of #59; is there a difference or can I close this one?

**Comment by cmdm** [comment] 2020-04-06 13:08
The issues #59 and #63 were wrongly  copy/pasted.
I Confirm for this issue  -> The device shall monitor the battery voltage and trig a **medium** priority alarm 21 when voltage is at **12.3V**

**Closed** 2020-04-17 11:06 UTC
Labels: regulatory, software
